germsvel/phoenix_test

- lib/phoenix_test/assertions.ex
- test/phoenix_test/assertions_test.exs
Allow using `refute_has` in pipes in the same way `assert_has` already works:
Fixes #7
> Allow piping from refute_has

- lib/phoenix_test/assertions.ex
- test/phoenix_test/assertions_test.exs
As part of its assertion error messages, PhoenixTest outputs HTML elements that match the query selector but do not
contain the requested text. Currently it only works for elements that only contain one child, and breaks otherwise. It
is sometimes useful to assert that a word will be present in a complex structure (maybe generated, like the modal popup
from `PetalComponents`) without coupling the code too much to the internal DOM of the structure.
Proposal: allow complex structures but not assuming only one child by default, and use `Floki.raw_html(content, pretty: true)` to render the error message.
> Fix formatting found elements with nested children

- lib/phoenix_test/assertions.ex
- test/phoenix_test/assertions_test.exs
Currently, assertions `assert_has` and `refute_has` raise `RuntimeError`
```
1) test index shows empty states (Manage.PageLiveTest)
apps/manage/test/manage/live/page_test.exs:6
** (RuntimeError) Could not find any elements with selector "span#bar".
code: |> assert_has("span#bar", "foo")
stacktrace:
(phoenix_test 0.2.1) lib/phoenix_test/assertions.ex:17: PhoenixTest.Assertions.assert_has/3
test/manage/live/page_test.exs:9: (test)
```
This works, but it's more common for assertion helpers to raise `ExUnit.AssertionError` instead, as it signals that
there is something wrong with what the test author is asserting vs. something wrong with the setup as such.
This PR introduces `AssertionError` to the `Assertions` module, and only there. This is how output of the same test
looks like:
```
1) …
```
> Raise AssertionError instead of RuntimeError

- lib/phoenix_test/html/form.ex
- test/phoenix_test/html/form_test.exs
- test/phoenix_test/static_test.exs
- test/support/page_view.ex
In the current version, `fill_form` can't be used if the fields are no direct children of the form element.
This PR changes the `build_fields` function to use Floki in order to find all input, select and textarea elements that are somewhere in the tree of the form element.
> Use Floki to find nested fields

- lib/phoenix_test/live.ex
- test/phoenix_test/live_test.exs
- test/support/index_live.ex
Closes #19 
What changed?
============
Our `Live` implementation doesn't handle form redirects, be they to another LiveView with `push_navigate/2` or to a static page via `redirect/2`.
This commit updates the implementation to follow redirects the same way we follow redirects when we click on links.
Testing note
-----------
We also create a new describe block to encapsulate all the testing for `fill_form/3` + `click_button/2`.
> Handle form redirects in Live pages

- lib/phoenix_test/static.ex
- test/phoenix_test/static_test.exs
- test/support/page_controller.ex
- test/support/page_view.ex
- test/support/router.ex
What changed?
============
Commit 531e5e9 updated Live form submissions to follow redirects to other LiveView and Static pages.
This commit does the same but for Static pages.
Thus, now when a `fill_form` + `click_button`, a single-field form `click_button`, or a `submit_button` redirects, we follow the redirect to the other page -- whether that be a LiveView or a static page.
> Handle form redirects in Static pages

- lib/phoenix_test/live.ex
- test/phoenix_test/live_test.exs
- test/support/index_live.ex
- test/support/page_controller.ex
- test/support/router.ex
Closes #16
What changed?
=============
Currently, we assume that if you're in a LiveView page, you're trying to submit LiveView forms with `phx-submit`. But people can have regular forms in LiveView pages.
This commit handles that scenario.
In order to handle that we introduce an error message when there are neither a `phx-submit` nor an `action`. In theory, form's don't need an `action`. The form's `action` defaults to the same page (i.e. `"/"`).
But we don't want to just fallback to the normal form if there's no `action`. Instead we want to notify the user of an error -- we should expect a `phx-submit` or an `action`.
> Handle regular form submission from a LiveView page

- test/phoenix_test/live_test.exs
- test/support/index_live.ex
Fixes #17
Closes #25
What changed?
============
Commit 180dc0d updated our `Live` implementation of form field validations. That fixed an issue that was happening in nested forms in Live that was first documented in https://github.com/germsvel/phoenix_test/issues/17.
A helpful PR https://github.com/germsvel/phoenix_test/pull/25 created a failing test that reproduced the error, and we include a slightly modified version of the test here.
I thought this branch would fix the issue, but the issue was completely resolved by the work in the previously mentioned commit. So, this commit only introduces the additional test.
> Test nested forms in LiveView

- lib/phoenix_test/assertions.ex
- lib/phoenix_test/driver.ex
- lib/phoenix_test/live.ex
- lib/phoenix_test/static.ex
- test/phoenix_test/assertions_test.exs
- test/phoenix_test/live_test.exs
- test/phoenix_test/static_test.exs
- test/support/index_live.ex
- test/support/page_controller.ex
- test/support/page_view.ex
- test/support/router.ex
Closes #4
What changed?
=============
We add support to assert and refute the page "title". The title is still visible by a user and is thus nice to support.
Because LiveView's `render/1` only returns the body of the HTML, we have to use LiveViewTest's`page_title/1` helper to get the title.
To keep parity, we introduce a new `render_page_title/1` driver function that we use in assertions to get the title of the page.
The assertion ignores whitespace when finding the title but the assertion only passes with equality. Thus, it doesn't match on a substring of the title.
> Add assert_has/refute_has "title"

- lib/phoenix_test/html/data_attribute_form.ex
- lib/phoenix_test/static.ex
- test/phoenix_test/html/data_attribute_form_test.exs
- test/phoenix_test/static_test.exs
- test/support/page_view.ex
What changed?
=============
Phoenix allows form submissions through data attributes: `data-to`, `data-method` and `data-csrf`.
That comes from the `Phoenix.HTML` library's little [JS snippet]:
```js
function handleClick(element, targetModifierKey) {
var to = element.getAttribute("data-to"),
method = buildHiddenInput("_method", element.getAttribute("data-method")),
csrf = buildHiddenInput("_csrf_token", element.getAttribute("data-csrf")),
form = document.createElement("form"),
submit = document.createElement("input"),
target = element.getAttribute("target");
form.method = (element.getAttribute("data-method") === "get") ? "get" : "post";
form.action = to;
form.style.display = "none";
if (target) form.target = target;
else if (targetModifierKey) form.target = "_blank"; …
```
> Handle a/buttons with `data-to` & `data-method` (Static)

- lib/phoenix_test.ex
- lib/phoenix_test/driver.ex
- lib/phoenix_test/live.ex
- lib/phoenix_test/open_browser.ex
- lib/phoenix_test/static.ex
- test/phoenix_test/live_test.exs
- test/phoenix_test/static_test.exs
- test/support/page_view.ex
Hey German!
Me again.
First off I'd like to say that I'll be totally cool if you don't think this belongs in PhoenixTest, but I did a quick implementation and wanted to create the PR to get the discussion going.
So this introduces a `preview/1` function which is essentially a wrapper around `Phoenix.LiveViewTest.open_browser/1`.
PhoenixTest's functions are all pipeable taking in a "session" as the first arg.  With `open_browser` essentially being `IO.inspect` for LiveViewTest, we want to be able to stick one in the middle of a pipeline.  We can't use `open_browser` for this since it takes a `Phoenix.LiveViewTest.View`.  Instead we have to change:
```elixir
conn
|> click_link("foo")
|> fill_form("form", foo: %{bar: "baz"})
|> click_button("Submit")
|> assert_has("Profit!")
```
into: …
> Add `open_browser/1`

- lib/phoenix_test.ex
- lib/phoenix_test/driver.ex
This adds `@doc false` to `open_browser/2` (only used for tests) so that `mix docs` doesn't error out on us.
> Only document `open_browser/1`

- lib/phoenix_test/assertions.ex
- lib/phoenix_test/html/form.ex
- lib/phoenix_test/query.ex
This PR adds a minimal `@doc` and `@moduledoc` for the following modules:
- Query
- Assertions
- Form
Overall the other modules seem to be well-covered with documentation on the file: `lib/phoenix_test.ex`
The initial conversation was tracked on #29
> Improve doc and moduledoc

- .github/workflows/ci.yml
- mix.exs
Closes #38 
Elixir 1.5 came out in June 2023. See the [announcement].
We should be able to support that.
[announcement]: https://elixir-lang.org/blog/2023/06/19/elixir-v1-15-0-released/
> Relax Elixir version requirement to Elixir 1.15

- lib/phoenix_test.ex
- test/phoenix_test/live_test.exs
- test/phoenix_test/static_test.exs
- test/support/redirect_live.ex
- test/support/router.ex
Closes #41
What changed?
=============
Currently, `PhoenixTest.visit/2` doesn't follow redirects. That's a helpful feature to have since (a) other links, buttons, etc. follow redirects (so it's expected), and (b) for scenarios like testing authentication in an app (imagine testing that you visit a page and you are redirected to a different page).
This commit adds redirection and tests it from both the Static and Live implementations -- even though the implementation is the same for both. It all happens in `PhoenixTest.visit/2`.
> Follow redirects on `PhoenixTest.visit/2`

- lib/phoenix_test.ex
- lib/phoenix_test/assertions.ex
- test/phoenix_test/assertions_test.exs
- test/support/router.ex
Closes #43
What changed?
=============
In commit 3756a47, we added a `PhoenixTest.assert_has/2` helper because there are cases when we want to assert an element is present WITHOUT specifying the text (e.g. an input where the `value=` attribute is what the user sees).
We now introduce a similar `refute_has/2` helper that doesn't require passing text for the same reasons.
Note: we also remove an unused pipeline in the test router.
> Add `PhoenixTest.refute_has/2`

- lib/phoenix_test/live.ex
- lib/phoenix_test/query.ex
- lib/phoenix_test/static.ex
- test/phoenix_test/live_test.exs
- test/phoenix_test/query_test.exs
- test/phoenix_test/static_test.exs
- test/support/index_live.ex
- test/support/page_view.ex
What changed?
=============
Our implementation of `click_button` assumes a little too much when it's preceded by a `fill_form` (meaning we have an "active form").
We assume that if you're clicking a button you're trying to submit the active form. But it could be equally true that we're cancelling the form (or as our Live test shows, that you're resetting the form, or in the case of our Static test that you're just clicking a completely different button).
So... we have to make our errors a little less helpful but allow for a better experience.
Instead of validating that the button is a submit button and raising if it isn't (which is actually confusing if you're trying to, say, cancel a form submission -- "of course it's not submit button! We're cancelling the form!"), we now check if the …
> Do not assume submit button after fill_form

- lib/phoenix_test/assertions.ex
- lib/phoenix_test/selectors.ex
- test/phoenix_test/assertions_test.exs
We add a `count:` option to `assert_has/2` and `refute_has/2` (making them 3-arity functions)
That allows people to test things like the exact number of elements in a list (e.g. with `.posts`):
```elixir
|> assert_has(".posts", count: 3)
```
Or refuting an exact number of elements:
```elixir
|> refute_has(".posts", count: 2)
```
(i.e. refute that there are 2 posts. 1 post is fine. More than 2 is fine).
What about `text` functions?
----------------------------
For now, we leave the other 3-arity assert and refute functions as they are -- meaning they take the `text` as the third argument.
Before we officially roll out this `count:` option, it would be nice to bring the text functions inline, but rather than turning them into 4-arity functions, we should make the text itself an option.
In …
> Add `count` on `assert_has/2` and `refute_has/2`

- lib/phoenix_test.ex
- lib/phoenix_test/assertions.ex
- lib/phoenix_test/query.ex
- test/phoenix_test/assertions_test.exs
- test/phoenix_test/query_test.exs
Resolves https://github.com/germsvel/phoenix_test/issues/27
What changed?
=============
We add an `at` option to `assert_has/3` and `refute_has/3` to assert against a specific position.
This is helpful if, for example, you want to assert what is the text of the second element in a list:
```elixir
assert_has("li", at: 2, text: "Hello world")
```
> Add `at` to assert against position

- lib/phoenix_test/live.ex
- test/phoenix_test/live_test.exs
- test/phoenix_test/static_test.exs
- test/support/index_live.ex
- test/support/page_2_live.ex
- test/support/page_controller.ex
- test/support/page_view.ex
Resolves https://github.com/germsvel/phoenix_test/issues/55
What changed?
============
When we `click_link` we follow redirects. But in `Live`, we only follow the redirect once. This commit updates the code so that we continue following them until we get a mounted LiveView or an HTML response.
The `Static` implementation already followed links more than once, but we add a test here to keep the implementation tests at the same level.
> Follow multiple redirects in Live

- lib/phoenix_test.ex
- lib/phoenix_test/assertions.ex
- test/phoenix_test/assertions_test.exs
Resolves https://github.com/germsvel/phoenix_test/issues/32
What changed?
============
We add two new assertion helpers to assert on the current path: `assert_path` and `refute_path`. Both helpers have a 2 and 3 arity versions. The 3-arity version takes a `query_params` key to assert on the query params.
We do not handle other optional arguments (such as `host` or `scheme`), though we could see this being extensible in the future with those options.
> Add `PhoenixTest.assert_path` and `refute_path`

- lib/phoenix_test/assertions.ex
- test/phoenix_test/assertions_test.exs
Resolves https://github.com/germsvel/phoenix_test/issues/64
What changed?
============
Our `assert_has/3` and `refute_has/3` helpers with `"title"` behave differently from the rest of our assertion helpers.
By default our other assertion helpers perform a match (`=~`) operation. Our "title" assertion performs an equality (`==`) operation.
In addition to being different from the rest, it's annoying because we typically render the title with a `<.live_title>` tag which has newlines and spaces.
We fix that in this commit and allow people to pass `exact: true` to match exactly.
> Fix assert_has/refute_has title matching exactly

- lib/phoenix_test.ex
- lib/phoenix_test/assertions.ex
- lib/phoenix_test/live.ex
- lib/phoenix_test/static.ex
- test/phoenix_test/assertions_test.exs
Partially handles https://github.com/germsvel/phoenix_test/issues/62
What changed?
=============
We improve our `assert_path` and `refute_path` implementation to partially handle live navigation. For now, we handle `<.link navigate>` options but we do not support `<.link patch>`
Patching is done at the LiveView process level, and we need to figure out how to best handle that.
For now, we release this fix to improve the experience, but we include a warning in the docs that the helpers do not support patching.
> assert_path/refute_path partially handle Live Navigation

- lib/phoenix_test/form.ex
- test/phoenix_test/form_test.exs
Resolves #https://github.com/germsvel/phoenix_test/pull/67
What changed?
============
From #67:
> When submitting a form with a checkbox that has an accompanying hidden
input (to populate the params when the checkbox is not checked), our current implementation grabs the value in the hidden input and ignores the later checkbox regardless of whether it is checked.
That's happening because our value is being overridden by the later inclusion of "pre-filled" inputs. The last `put_form_data` call in our `Form`'s attempt to populate the data (meant to capture inputs with `text` or with no type) has a lot of exclusion CSS (i.e. `:not()`) which did not exclude hidden inputs.
We change our queries to be more explicit by splitting the query to grab text and default text inputs into two queries …
> Fix checked checkbox being overridden by hidden input

- lib/phoenix_test/assertions.ex
- lib/phoenix_test/live.ex
- lib/phoenix_test/static.ex
- lib/phoenix_test/utils.ex
- test/phoenix_test/assertions_test.exs
- test/support/index_live.ex
Resolves #62 
What changed?
=============
Unlike regular page navigations and live navigations, live patching doesn't actually exhibit different behavior after a `render_click` or `render_submit` (like a live navigate does, for example).
That makes "knowing" the current path hard when a live patch has been triggered.
An ugly attempt
---------------
Live patches in LiveView tests seem to come through messages (see the `assert_navigate` private function). It's hard to intercept those messages since we don't own the client proxy.
An alternative route (which we take here) is to use what LiveViewTest exposes to us. And that's `assert_patch/2`.
The `assert_patch/2` helper returns the path that we've been patched to. The downside is that it's an assertion... so it raises if nothing's been …
> Fix `assert_path`/`refute_path` to handle live patching

- lib/phoenix_test/form.ex
- test/phoenix_test/live_test.exs
- test/phoenix_test/static_test.exs
- test/support/index_live.ex
- test/support/page_view.ex
**Given**
a "static" form
```html
<input name="user[name]" value="Ada" />
<button name="user[action]" value="save">Save</button>
```
**When**
I click on the "Save" button
**Then** (actual behaviour)
this is submitted
```ex
form_data = %{"user" => %{"name" => "Ada"}}
```
**Instead of** (expected behaviour)
```ex
form_data = %{"user" => %{"name" => "Ada", "action" => "save"}}
```
Already correctly implemented by LiveView test.
> Fix: Deep merge nested form button value (static)

- lib/phoenix_test/utils.ex
- test/phoenix_test/live_test.exs
- test/phoenix_test/static_test.exs
- test/support/index_live.ex
- test/support/page_view.ex
**Given**
a "static" or "live" form
```html
<input type="checkbox" name="subscribe?" value="on" />
```
**When**
I `check/2` the box and submit the form
**Then** (actual behaviour)
this is submitted
```ex
form_data = %{"subscribe" => "on"}
```
**Instead of** (expected behaviour)
```ex
form_data = %{"subscribe?" => "on"}
```
> Fix: Preserve '?' in checkbox name

- lib/phoenix_test/field.ex
- test/phoenix_test/live_test.exs
- test/support/index_live.ex
Unchecking checkboxes in nested forms currently crashes with 
```
** (FunctionClauseError) no function clause matching in Floki.Selector.Parser.do_parse/2
The following arguments were given to Floki.Selector.Parser.do_parse/2:
[{~c"]", 1}]
%Floki.Selector{id: nil, type: "input", classes: [], attributes: [%Floki.Selector.AttributeSelector{match_type: :equal, attribute: "name", value: "payer", flag: nil}, %Floki.Selector.AttributeSelector{match_type: :equal, attribute: "type", value: "hidden", flag: nil}], namespace: nil, pseudo_classes: [], combinator: nil}
Attempted function clauses (showing 10 out of 21):
defp do_parse([], selector)
defp do_parse([{:close_parentesis, _} | t], selector)
defp do_parse([{:comma, _} | t], selector)
defp do_parse([{:identifier, _, namespace}, …
```
> Fix uncheck/2 in nested forms

- lib/phoenix_test/form.ex
- test/phoenix_test/live_test.exs
- test/phoenix_test/static_test.exs
- test/support/index_live.ex
- test/support/page_view.ex
Current implementation performs multiple passes over form defaults before merging in "user"-supplied form data.
`Map.merge` works well for flat forms where `name` attributes on inputs are not nested. When nesting is in place and
attributes look like this: `user[name]`, this approach breaks as default check boxes override hidden inputs, select
defaults override everything else, etc. 
This patch uses replaces `Map.merge` with `DeepMerge.deep_merge` for form data helpers, in the same way it's already
done in some places in the live driver.
N.B. this bug occurs for the static driver but not for the live driver that already uses `DeepMerge`.
> Deep merge form data in nested/prefixed forms

- lib/phoenix_test.ex
- lib/phoenix_test/driver.ex
- lib/phoenix_test/live.ex
- lib/phoenix_test/static.ex
- test/phoenix_test/assertions_test.exs
Extracted from #74 
Allow more flexibility for Driver implementations.
Browser-based testing is inherently decoupled, and usually involves some retry/await concept to ensure the rendered web UI is up to date with the server side state.
Wrapping the assertion functions in the `Driver` protocol allows flexibility for browser-based Drivers:
- use built-in framework assertions (Wallaby, Playwright) that have an integrated retry
- build custom retry wrapper around `PhoenixTest.Assertions`
> Refactor: Move assertions into 'Driver' protocol

- lib/phoenix_test/form.ex
- test/phoenix_test/form_test.exs
- test/phoenix_test/live_test.exs
- test/phoenix_test/static_test.exs
- test/support/index_live.ex
- test/support/page_view.ex
This PR adds support for default / pre-filled values in `<textarea>` form elements. The default `put_form_data` helper function can't work here, as `<input>` elements have the value in an attribute but `<textarea>` holds it as a text child.
> Support default values on textareas

- lib/phoenix_test/query.ex
- test/phoenix_test/form_test.exs
- test/phoenix_test/query_test.exs
Resolves #97
What changed?
=============
It turns out that Chrome and Firefox don't accept `#text?` as a valid selector. But having a `?` in an element's `id` seems to be valid HTML.
Thank to https://github.com/philss/floki/issues/583 for the info.
To support that, we update our `Query.find_by_label` function to query by `[id='<id>']` instead of using `#<id>`.
> Query associated element with `[id='<id>']`

- lib/phoenix_test/field.ex
- lib/phoenix_test/live.ex
- test/phoenix_test/field_test.exs
- test/phoenix_test/live_test.exs
- test/support/index_live.ex
Part of https://github.com/germsvel/phoenix_test/issues/112
What changed?
============
We add the ability for radio buttons (i.e. `input type="radio"`) to live outside of forms in LiveViews.
Typically, people would want to add a `phx-click` to the radio button and rely on the input's `value` when it comes through the params.
Thus, we handle that specific case. We follow the pattern established in `click_button` to check:
1. If the input has a phx-click
2. If the input belongs to a form, or
3. Raise an error informing user that we expect the input to have one or the other
NOTE: we do not yet handle `phx-value-*` being passed. We might have to, but it seems that in radio buttons, that's unlikely to be the need. By default, Phoenix sends the input's `value`, so that's what we should rely on. …
> Handle radio buttons with phx-click

- lib/phoenix_test/field.ex
- lib/phoenix_test/form_data.ex
- lib/phoenix_test/live.ex
- lib/phoenix_test/select.ex
- lib/phoenix_test/static.ex
- test/phoenix_test/field_test.exs
- test/phoenix_test/live_test.exs
- test/phoenix_test/select_test.exs
- test/support/index_live.ex
Part of https://github.com/germsvel/phoenix_test/issues/112
What changed?
============
We update the `select` helper to work with `phx-click` outside of forms.
Note that the `phx-click` has to be on the option being selected, not on the `select` tag itself.
For multi-selects, we trigger a `phx-click` for each option selected. That emulates how Phoenix receives events from the browser with multi-select.
Restructuring
-------------
As part of this work, we extract a `Select` module to keep all the select logic. Now `Field` could probably be renamed `Input`, since it's dealing with inputs (text, radio, checkbox).
Finally, we move the `Field.to_form_data` function into a `FormData` module. We originally though to make it a protocol, but it seems overkill. For now, pattern matching just like …
> Allow select to work with phx-click

- lib/phoenix_test/live.ex
- test/phoenix_test/live_test.exs
- test/support/index_live.ex
Supersedes https://github.com/germsvel/phoenix_test/pull/109 
Resolves https://github.com/germsvel/phoenix_test/issues/112
What changed?
=============
We update `check` and `uncheck` to work with `phx-click` attributes
outside of forms.
The `check` case is straightforward. The `uncheck` is more complicated.
For the `uncheck` case, we first look for an checkbox that is visible.
That's contrary to what we were doing with form checkboxes -- where we
need a hidden input -- because a single checkbox can have a `phx-click`
for checking and unchecking. That removes the need for the hidden input
(like forms need).
So, if we find the checkbox and it has a `phx-click` attached, we
trigger that. If not, we check if the field belongs to a form. If so, we
find the hidden "uncheckbox" to get the value. …
> Check/uncheck work with phx-click outside forms

- lib/phoenix_test/element.ex
- test/phoenix_test/element_test.exs
Closes https://github.com/germsvel/phoenix_test/pull/124
What changed?
=============
When we build elements, we infer their selector based on `id` or all of their other attributes.
Up until now, we grabbed everything expect the `class`. But `phx-*` attributes can also have complex data when they're `LiveView.JS` actions. So, we should ignore that too when creating the selector.
> Ignore `phx-*` attrs when inferring selector

- lib/phoenix_test.ex
- lib/phoenix_test/live.ex
- lib/phoenix_test/query.ex
- lib/phoenix_test/select.ex
- lib/phoenix_test/static.ex
- test/phoenix_test/live_test.exs
- test/phoenix_test/static_test.exs
- test/support/index_live.ex
- test/support/page_view.ex
Find select option by exact match. Allows disambiguating options that share a common substring.
E.g.
```html
<select>
<option value="orc">Orc</option>
<option value="other_orc">Other Orc</option>
</select>
```
Currently, there is no way to distinguish `Orc` and `Other Orc` (`Found more than one element`).
> Find select option via 'exact=true' (breaking change)

- lib/phoenix_test/form.ex
- test/support/page_view.ex
Given
```html
<input value="123" />
```
submit the form without error.
Just omit the input without a name attribute.
> Fix: Don't error on input without name attribute

- lib/phoenix_test.ex
- lib/phoenix_test/select.ex
- test/phoenix_test/live_test.exs
- test/phoenix_test/static_test.exs
What changed?
=============
PR #118 (commit dc7ba01) introduced the ability to pass `exact: true | false` to `select`.
That need arose because we were doing substring matches in select options. So, if a form had the following two options:
```html
<option value="orc">Orc</option>
<option value="other_orc">Other Orc</option>
```
there was no way to distinguish between them!
To provide backwards compatibility, I suggested we include the ability to pass the `exact: false` option. But I now think that was a bad suggestion.
It seems to me that options should always be exact, and the previous implementation was basically a bug.
Why not leave the `:exact` option just in case?
----------------------------------------------
[Other work](https://github.com/germsvel/phoenix_test/issues/127) is …
> 🛠️ Select options are always exact

- lib/phoenix_test.ex
- test/phoenix_test/live_test.exs
- test/phoenix_test/static_test.exs
- test/support/index_live.ex
- test/support/page_view.ex
Closes #107, #127
What changed?
============
We update all form helpers (e.g. `fill_in`, `check`, etc.) to take in the `exact` option. The option allows forms to target labels exactly (default) or inexactly.
That's helpful when you have labels that have more complex contents -- for example, they might have nested HTML.
> ✨ Form helpers now take `:exact` option

- .github/workflows/ci.yml
- .tool-versions
We also add elixir 1.17 to the CI matrix, but we keep otp 26 since only elixir 1.17 works with otp 27.
> Set elixir 1.17 and erlang 27 in `.tool-versions`

- lib/phoenix_test.ex
- lib/phoenix_test/static.ex
- test/phoenix_test/live_test.exs
- test/phoenix_test/static_test.exs
Resolves #126 
What changed?
============
In order to emulate browser behavior a little bit better, we want to copy headers across redirects.
Whenever we dispatch to the endpoint, the `Phoenix.ConnTest.recycle/2` automatically gets called. But by default it only recycles "accept", "accept-language", and "authorization".
This commit calls it manually copying _all_ request headers.
For more, see docs on
https://hexdocs.pm/phoenix/Phoenix.ConnTest.html#recycle/2
> Recycling receives a connection and returns a new connection,
containing cookies and relevant information from the given one.
> This emulates behaviour performed by browsers where cookies returned
in the response are available in following requests.
> By default, only the headers "accept", "accept-language", and
"authorization" are …
> Copy headers across redirects

- lib/phoenix_test/active_form.ex
- lib/phoenix_test/live.ex
- lib/phoenix_test/static.ex
- test/phoenix_test/active_form_test.exs
- test/phoenix_test/live_test.exs
- test/support/index_live.ex
Resolves #105 
What changed?
=============
At some point, a page's default data (parsed in `Form`) would become part of the `ActiveForm` form data.
That meant that if the data on the page changed, the stuff that had been filled in on a previous form action would prevail because it was acting as part of the "active form" data.
This is the way this should work (done in this commit):
- `ActiveForm` should _ONLY_ keep track of fields that have been filled in. The rest of the data to submit should come from `form.form_data`. We should not copy it and keep track of it there.
- `click_button`, `submit`, and anything else that triggers changes (like `phx-change`) should know to combine `form.form_data ++ ActiveForm.form_data` before sending it to the server.
- We should probably keep track of …
> 🛠️ Fix active form vs form data loading

- lib/phoenix_test/form_payload.ex
- test/phoenix_test/form_payload_test.exs
Closes #110 
What changed?
=============
Currently, `FormData` keeps the data passed as a list of tuples. That's not an optimal strategy since it doesn't deal with duplicates well.
That being said, there are two competing behaviors that we need to handle:
- One the one hand, we want to keep duplicates of list-like `name`s (e.g. `{"contact[]", "email"}`.
- On the other hand, we don't really want to keep duplicates of the same operation done multiple times (e.g. `[{"email", "frodo@example.com"}, {"email", "aragorn@example.com"}]`).
In the latter case, we can imagine a user doing a `fill_in` twice, where the email field changed twice. In the first case, we might have something like a checkbox where the user can check multiple values.
Like we said, a list of tuples doesn't seem to be the …
> Deduplicate data passed to FormPayload

- .envrc
- lib/phoenix_test/element/form.ex
- lib/phoenix_test/live.ex
- test/phoenix_test/live_test.exs
- test/support/index_live.ex
> Support phx-trigger-action

- lib/phoenix_test/query.ex
- test/phoenix_test/live_test.exs
- test/phoenix_test/query_test.exs
- test/support/index_live.ex
Found via #136 
```html
<label for="greeting">Hello</label>
<input id="greeting" />
<label>Hello <input id="second_greeting" /></label>
```
```ex
session
|> fill_in("Hello", with: "world")
```
```ex
ArgumentError: Found many elements with label "Hello" and matching the provided selectors
```
No error. Label with explicit `for` wins, other one ignored.
> Fix: Raise error if implicit + explicit label found

- lib/phoenix_test/live.ex
- test/phoenix_test/live_test.exs
- test/support/index_live.ex
- test/support/router.ex
The added behavior of copying headers wasn't working in my application, and after toying around with a local path dependency, I found that in the `:live_redirect` case the headers weren't being copied. While adding the call to `recycle/2` with the list of all headers made things work again, I wasn't sure why all of your tests were passing.
Included in this PR is a scenario the more closely mirrors what is happening in my application, where the cookie session is modified in a Plug. This scenario provokes the error, and my second commit adds the additional header copy to pass the tests. I suspect the test case could be integrated into the test suite better.
> Live redirect copy headers

- lib/phoenix_test/element/form.ex
- test/support/index_live.ex
A disabled select currently causes all input functions to fail.
Example:
```
** (ArgumentError) could not find non-disabled input, select or textarea with name "disabled_select" within:
...
(phoenix_live_view 1.0.0) lib/phoenix_live_view/test/live_view_test.ex:1106: Phoenix.LiveViewTest.call/2
(phoenix_test 0.4.2) lib/phoenix_test/live.ex:296: PhoenixTest.Live.submit_form/4
test/phoenix_test/live_test.exs:359: (test)
```
Fix: Ignore disabled selects when building initial form data, just as we ignore all other disabled input types.
> Fix: Don't fail for disabled select

- lib/phoenix_test.ex
- lib/phoenix_test/conn_handler.ex
- lib/phoenix_test/driver.ex
- lib/phoenix_test/live.ex
- lib/phoenix_test/static.ex
Supersedes #149 
In order to support external libraries implementing the `Driver` protocol, we move the `visit/2` call out of `PhoenixTest`. When it's a `Plug.Conn` struct, we delegate to `ConnHandler.visit/2` (not the best name, but good enough for now).
> Add `visit/2` to Driver protocol

- lib/phoenix_test/html.ex
- test/phoenix_test/live_test.exs
- test/support/index_live.ex
Similar to other feature testing libraries.
Wallaby
>  Matches any element by its inner text.
`~s{.//*[contains(normalize-space(text()), "#{selector}")]}`
[xpath.ex](https://github.com/elixir-wallaby/wallaby/blob/c144c92e8bc1812c1f712cc1f1c652c4d2c7ce4b/lib/wallaby/query/xpath.ex#L80)
https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/normalize-space
Playwright
> Matching by text always normalizes whitespace, even with exact match. For example, it turns multiple spaces into one, turns line breaks into spaces and ignores leading and trailing whitespace.
https://playwright.dev/docs/locators#get-by-text
> Normalize whitespace (find label with line breaks)

- .github/workflows/ci.yml
- .tool-versions
We update the `.tool-versions` file to use Elixir 1.18, and update
the CI matrix to use OTP 27 and include Elixir 1.18.
We could probably drop Elixir 1.15, but we don't do it if we don't need
to yet.
> Use Elixir 1.18

- lib/phoenix_test.ex
- lib/phoenix_test/assertions.ex
- test/phoenix_test/assertions_test.exs
To cover scenarios where a user interaction creates a temporary entity which is referred to in the path.
Allow wildcards in `assert_path`.
Example:
```elixir
conn
|> visit("/")
|> click("new chat room")
|> assert_path("/chat/*")
```
Each wildcard `*` maps to exactly one part in the uri, so
`/user/*/profile` will accept `/user/123/profile`, but not `/user/profile` or `/user/123/public/profile`
> Allow wildcards in assert_path

- lib/phoenix_test/live.ex
- test/phoenix_test/live_test.exs
- test/support/web_app/index_live.ex
`render_upload` can emit errors that are not redirects. `upload/4` now throws nice errors for the following `render_upload` errors: [:too_large, :too_many_files, :not_accepted]. We let new/unknown errors simply fail at the case match so they can be implemented in the future. Sessions and redirects are passed through to `maybe_redirect` as before.
Fixes #167
> fix: :bug: throw nice error messages for `render_upload` errors

- lib/phoenix_test/live.ex
- lib/phoenix_test/session_helpers.ex
- lib/phoenix_test/static.ex
- test/phoenix_test/session_helpers_test.exs
Resolves #185 
What changed?
============
This updates `within/3` to be able to nest `within/3` for both Live and Static implementations.
Though not strictly required (since right now the last within always wins), it can be confusing if someone nests `within/3` and it unexpectedly finds something that would've been left out by the "outer" within.
As part of this work, we create a `SessionHelpers` module to keep the `within` implementation that was duplicated across `Live` and `Static`. It's not the best module name, but it works for now. It might attract more logic and get a better name in the future.
> Allow nesting of `within/3`

- .github/workflows/ci.yml
We drop Elixir 1.15 and 1.16 so we can rely on OTP 27.
> Simplify CI testing matrix

- lib/phoenix_test.ex
- test/phoenix_test/live_test.exs
- test/phoenix_test/static_test.exs
- test/phoenix_test_test.exs
- upgrade_guides.md
Resolves #166 
What changed?
============
Our `select` form helper takes in the option text first, and then it takes the label text in a `:from` argument.
That is confusing since every other form helper takes in the label first (as a positional argument), and then takes the "other value" (when it has one) as a keyword list.
We did it like that because it seemed to read somewhat naturally, and because of previous art (that's how Capybara's API had it). But really, the confusion it causes isn't worth the way it reads.
So, we deprecate the `:from` key in favor of passing the option text in` :option`.
Thus, we have to change:
```diff
- |> select("Option 1", from: "Select Label")
+ |> select("Select Label", option: "Option 1")
```
For now, things don't break. We include a deprecation warning …
> Deprecate `select` with `:from` in favor of `:option`

- lib/phoenix_test/element.ex
- test/phoenix_test/element_test.exs
Resolves #176 
What changed?
============
Our `Element.build_selector` function is used to create selectors for different elements. By default, it ignores `phx-*` attributes since they can are complex when they use LiveView.JS.
But sometimes people want to rely on the `phx-*` attribute to target elements. One example was when using them for `form` elements with `phx-submit`s that only have an event name.
So, we modify our `build_selector` function to include simple `phx-*` values by identifying LiveView.JS through a heuristic -- when it's json encoded, it has a `[[` to start.
> Include simple `phx-*` attributes in selectors

- lib/phoenix_test/assertions.ex
- lib/phoenix_test/utils.ex
- test/phoenix_test/assertions_test.exs
- test/phoenix_test/utils_test.exs
Resolves #168
What changed?
============
We improve `assert_path` to handle query params that have lists.
There are many cases when we want to assert the query includes things like `users[]=frodo&users[]=sam`.
The assertion would present those as a list in the map:
```elixir
assert_path("/some/path", query_params: %{users: ["frodo", "sam"]})
```
This commit makes it so that we can do that.
> `assert_path` handles query params with []

- lib/phoenix_test/assertions.ex
- test/phoenix_test/assertions_test.exs
Initially, there was no way to assert that a path had no query params. If you passed into `assert_path` `query_params: ""` or `query_params: nil` you would get: `(FunctionClauseError) no function clause matching in PhoenixTest.Utils.stringify_keys_and_values/1` This is because `Utils.stringify_keys_and_values` is expecting a map.
If you passed in `query_params: %{}`, you would get: `Empty map results in "Expected query params to be "" but got nil.` This is because URI.parse returns `nil` when a query param is not present.
The fix is to assert true if either the query_params match the passed in expected params or if the parsed query_params are `nil` and the expected params are an empty map.
> Allow empty maps to be passed into assert_path as query_params

- lib/phoenix_test/element/form.ex
- test/phoenix_test/element/form_test.exs
Supersedes #178 
The core change was introduced in #178. This PR adds tests to those changes. 
GitHub doesn't let me rebase and push over that branch, so this PR was created to supersede #178 but includes those changes. 
What changed? 
===========
We update our `Form` parsing to include all prefilled values for most input types that are "simple" or "text-like" (contrary to, say, a checkbox that must be selected in order to get the prefilled `value`).
> Fix: handle prefilled values for most input types

- lib/phoenix_test.ex
- lib/phoenix_test/assertions.ex
- test/phoenix_test/assertions_test.exs
- test/support/web_app/page_view.ex
Resolves #181 
What changed?
============
We introduce a new `:value` option to `assert_has/3` and `refute_has/3`.
It allows us to make assertions about the value of an `<input>`, `<option>`, etc. That's mostly helpful when we want to check the state of an input.
The option cannot be combined with `:text` (we raise), and it isn't compatible with `:exact` (the value is always expected to be exact).
Aside from that, all other options are allowed (e.g. `:count`, `:at`, etc.)
> Adds asserting & refuting by `:value`

- lib/phoenix_test/element/form.ex
- lib/phoenix_test/form_data.ex
- lib/phoenix_test/live.ex
- test/phoenix_test/element/form_test.exs
- test/phoenix_test/form_data_test.exs
- test/phoenix_test/live_test.exs
- test/support/web_app/index_live.ex
Supersedes #171 and fixes #170
What changed?
============
Contrary to Static forms, LiveView forms can dynamically remove inputs, selects, etc.
Right now our form submission assumes every input that has been filled (or defaulted) should remain when we submit the form. But that doesn't handle the case when the form changes as a result of user's behavior on the page.
This commit fixes that by comparing the form's elements right before submission with the data that we have gathered from user interactions. If the form no longer has a field with that `name` on it, we remove it from the form submission (assuming it's been removed one way or another).
> Handles LiveView forms that remove elements

- lib/phoenix_test.ex
- lib/phoenix_test/live.ex
- test/phoenix_test/live_test.exs
- test/support/web_app/index_live.ex
When a file is selected in the browser, phx-change is triggered on the form. This changes the behaviour of upload/4 to be closer to the browsers behaviour. 
BREAKING CHANGE: users who previously worked around this issue may have phx-change called twice.
> feat: :sparkles: trigger phx-change on upload

- lib/phoenix_test.ex
- lib/phoenix_test/assertions.ex
- lib/phoenix_test/query.ex
- test/phoenix_test/assertions_test.exs
- test/phoenix_test/query_test.exs
- test/support/web_app/page_view.ex
Resolves #44 
What changed?
=============
Now that we've introduced the ability to assert the value of an element (i.e. a form field), we improve the `assert_has/3` and `refute_has/3` to allow asserting by `label`.
The `:label` option only works with `:value`, not with `:text`. It makes the options we can pass to `assert_has/3` and `refute_has/3` a little strange--you now need to know the correct incantation of options to pass--but it seems worth the trade-off.
If things get any more complicated, it may be worth adding helpers like `field/1` that would allow a more composable API (e.g. `assert_has(field(value: "foo", label: "bar"))`). But for now, this works as-is without having to introduce new helpers or modules.
> Adds: asserting by value and label

- lib/phoenix_test/conn_handler.ex
- test/phoenix_test/conn_handler_test.exs
Resolves #194 
What changed?
=============
Commit 668448ab introduced raising on paths that were not defined in the router.
That provides a nicer experience when TDDing, but people are using `assert_path` to assert they've landed on an external URL (think authentication failing or logging out of the app).
In those cases, the request is a 404. But since `assert_path` is just checking the `conn.request_path`, we're able to assert something about the path even if PhoenixTest cannot actually visit that external URL.
This commit adds a check to see if the path we're trying to validate with the router is internal or external.
- If external, we do not raise (since we might want to `assert_path`).
- If internal, we raise so that it's clear the path isn't defined in the application's router.
NOTE: …
> Do not raise non-existent path if URL is external

- lib/phoenix_test/utils.ex
- test/phoenix_test/assertions_test.exs
- test/phoenix_test/utils_test.exs
Similarly to https://github.com/germsvel/phoenix_test/issues/168, `assert_path/3` should be able to handle nested query params, given that [`Plug.Conn.Query` can generate it](https://hexdocs.pm/plug/1.18.0/Plug.Conn.Query.html#:~:text=Nested%20structures%20can%20be%20created%20via%20%5Bkey%5D%3A): 
```elixir
iex> Plug.Conn.Query.decode("foo[bar]=baz")
%{"foo" => %{"bar" => "baz"}}
```
> `assert_path` handles nested query params

- lib/phoenix_test/element/field.ex
- lib/phoenix_test/live.ex
- lib/phoenix_test/live_view_bindings.ex
- test/phoenix_test/live_test.exs
- test/support/web_app/index_live.ex
Closes: https://github.com/germsvel/phoenix_test/issues/237
Sorry of the delay, had to work through submission approval.
This PR updates `uncheck/3|4` to check if the checkbox has a `phx-click` attribute and either also has `phx-value` attributes or the `phx-click` attribute is a JS command with a value assigned, and makes sure those values are passed as params to the `handle_action/3` callback.
If there is a `phx-click` attribute but no identifiable values, the previous behavior of using an empty map for params is maintained for compatibility.
> support phx-value and JS command values with uncheck

- lib/phoenix_test/form_data.ex
- test/phoenix_test/form_payload_test.exs
Elements in lists/arrays in forms (referenced by unindexed `field_name[]`) have been aggregated in the order they appear in the HTML document before the refactoring in https://github.com/germsvel/phoenix_test/commit/b1400b3faee35f9e5f078422042b309895c00e51
Since then, the order has been the opposite.
This works in most cases, but sometimes the order is significant and flipping it can become problematic.
This PR reverts the order to the "natural" order of occurrence in the document.
> Preserve order of appearance for array inputs

- lib/phoenix_test/form_data.ex
- test/phoenix_test/form_data_test.exs
- test/phoenix_test/live_test.exs
- test/support/web_app/index_live.ex
Supersedes #224, #225, 
Closes #239 
What changed?
=============
When we refactored `FormData`, we lost the ability to have multiple selects and multiple checkboxes in some scenarios.
For example:
- when we have a default checkbox "checked" and add a new one
- when we use `select` multiple times in a row
This commit improves the merging behaviour of two FormData structs so that we can handle key names that allow for multi-selects (i.e. they end in `[]`)
Thanks to @ftes for providing test cases for these failures.
> Fix: allow multiple select and checkboxes

- lib/phoenix_test/element/button.ex
- test/phoenix_test/element/button_test.exs
- test/phoenix_test/live_test.exs
- test/support/web_app/index_live.ex
Resolves #252, #257
What changed?
=============
Whenever we pass a selector in `click_button/3`, we're correctly using the selector to find the button. But then we're incorrectly relying on the parsed button's data to generate a new selector.
That happens because we're no longer using the provided selectors. Instead, we use the parsed button's selector.
That's not typically a problem unless the selector provided had a descendant selector (meaning it was using data outside of the button itself). In those cases, subsequent attempts to use `button.selector` fail if there are duplicates on the page.
To fix that, we simply rely on the selector provided so long as it's something more complex than mere "button". If it's just "button", we know that the selector we can generate from the parsed …
> Fix: keep provided selector in `click_button/3`
